---
apiVersion: v1
kind: Service
metadata:
  name: sigc-client
  namespace: kypr
  labels:
    app: sigc
    component: client
spec:
  type: ClusterIP
  selector:
    app: sigc
    component: client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http