---
apiVersion: v1
kind: Service
metadata:
  name: sigc-signer
  namespace: kypr
  labels:
    app: sigc
    component: signer
spec:
  type: ClusterIP
  selector:
    app: sigc
    component: signer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http