---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigc-worker
  namespace: kypr
  labels:
    app: sigc
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigc
      component: worker
  template:
    metadata:
      labels:
        app: sigc
        component: worker
    spec:
      containers:
      - name: sigc
        image: registry.kypr.sh/sigc:1
        args:
        - "worker"
        envFrom:
        - secretRef:
            name: sigc
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 2Gi